// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id int64 `json:"id"`
}

type OrderResp struct {
	Id        int64  `json:"id"`
	GoodsName string `json:"goodsName"`
	GoodsId   int64  `json:"goodsId"`
}
