GRPC localhost:8080/goods.Goods/info

{
  "id": "1"
}

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:8888/order/getorder
Content-Type: application/json

{
  "id": 123
}

###
