// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package goodsclient

import (
	"context"

	"demo/goods/rpc/goods"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = goods.Request
	Response = goods.Response

	Goods interface {
		Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultGoods struct {
		cli zrpc.Client
	}
)

func NewGoods(cli zrpc.Client) Goods {
	return &defaultGoods{
		cli: cli,
	}
}

func (m *defaultGoods) Info(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := goods.NewGoodsClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}
